/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        h1:          ['"Syne"', 'system-ui', 'sans-serif'],
        h2:          ['"Syne"', 'system-ui', 'sans-serif'],
        h3:          ['"Syne"', 'system-ui', 'sans-serif'],
        'body-lg':   ['"Inter"', 'system-ui', 'sans-serif'],
        'body-md':   ['"Inter"', 'system-ui', 'sans-serif'],
        'label-caps':['"Space Grotesk"', 'system-ui', 'sans-serif'],
        code:        ['"Space Grotesk"', 'monospace'],
        sans:        ['"Inter"', 'system-ui', 'sans-serif'],
        display:     ['"Syne"', 'system-ui', 'sans-serif'],
        mono:        ['"Space Grotesk"', 'monospace'],
      },
      fontSize: {
        h1:          ['48px', { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '700' }],
        h2:          ['32px', { lineHeight: '1.2',  letterSpacing: '-0.01em', fontWeight: '600' }],
        h3:          ['24px', { lineHeight: '1.3',  letterSpacing: '0em',     fontWeight: '600' }],
        'body-lg':   ['18px', { lineHeight: '1.6',  fontWeight: '400' }],
        'body-md':   ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
        'label-caps':['12px', { lineHeight: '1.0',  letterSpacing: '0.1em',   fontWeight: '500' }],
        code:        ['14px', { lineHeight: '1.5',  fontWeight: '400' }],
      },
      colors: {
        background:              '#131313',
        surface:                 '#131313',
        'surface-dim':           '#131313',
        'surface-bright':        '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container':     '#201f1f',
        'surface-container-high':'#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant':       '#353534',
        'on-surface':            '#e5e2e1',
        'on-surface-variant':    '#ddc0be',
        'inverse-surface':       '#e5e2e1',
        'inverse-on-surface':    '#313030',
        outline:                 '#a48b89',
        'outline-variant':       '#564241',
        'surface-tint':          '#ffb3b0',
        primary:                 '#ffb3b0',
        'on-primary':            '#630c14',
        'primary-container':     '#e26c6c',
        'on-primary-container':  '#5a040f',
        'inverse-primary':       '#a23c3e',
        'primary-fixed':         '#ffdad8',
        'primary-fixed-dim':     '#ffb3b0',
        'on-primary-fixed':      '#410006',
        'on-primary-fixed-variant': '#832428',
        secondary:               '#abcdcd',
        'on-secondary':          '#143535',
        'secondary-container':   '#2e4e4e',
        'on-secondary-container':'#9dbfbe',
        'secondary-fixed':       '#c6e9e9',
        'secondary-fixed-dim':   '#abcdcd',
        'on-secondary-fixed':    '#002020',
        'on-secondary-fixed-variant': '#2c4c4c',
        tertiary:                '#c8bfff',
        'on-tertiary':           '#2d009d',
        'tertiary-container':    '#907eff',
        'on-tertiary-container': '#26008b',
        'tertiary-fixed':        '#e5deff',
        'tertiary-fixed-dim':    '#c8bfff',
        'on-tertiary-fixed':     '#190064',
        'on-tertiary-fixed-variant': '#442bb5',
        error:                   '#ffb4ab',
        'on-error':              '#690005',
        'error-container':       '#93000a',
        'on-error-container':    '#ffdad6',
        'on-background':         '#e5e2e1',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.125rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        xs:             '4px',
        sm:             '12px',
        base:           '8px',
        md:             '24px',
        lg:             '48px',
        xl:             '80px',
        'grid-gutter':  '24px',
        'grid-margin':  '40px',
        'spacing-xl':   '280px',
      },
      animation: {
        'fade-in':      'fadeIn 0.3s ease-out',
        'slide-up':     'slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
        'pulse-soft':   'pulseSoft 2s ease-in-out infinite',
        shimmer:        'shimmer 1.8s linear infinite',
      },
      keyframes: {
        fadeIn:    { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp:   { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        pulseSoft: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.4' } },
        shimmer:   { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
      boxShadow: {
        synapse: '0 0 40px rgba(226, 108, 108, 0.15)',
        panel:   '0 8px 32px rgba(0,0,0,0.5)',
      },
      backdropBlur: {
        glass: '12px',
      },
    },
  },
  plugins: [],
}